name: Cargo Update

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo update
        run: cargo update
      - name: Setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit changes if necessary
        run: |
          CHANGED=`git status --porcelain | wc -l`
          if [ $CHANGED -gt 0 ]; then
            git add Cargo.lock
            git commit -m "chore: Update Cargo.lock"
            git push
          fi
